#!/bin/bash
sudo apt-get update 
sudo apt-get install openjdk-8-jdk -y
sudo apt-get install openjdk-8-jre -y
sudo apt-get update
sudo apt-get install maven -y 
sudo apt-get update
export temp_mysql_password="root123"
export DEBIAN_FRONTEND=noninteractive
debconf-set-selections <<< "mysql-server mysql-server/root_password password $temp_mysql_password"
debconf-set-selections <<< "mysql-server mysql-server/root_password_again password $temp_mysql_password"
debconf-set-selections <<< "mysql-server-5.7 mysql-server/root_password password $temp_mysql_password"
debconf-set-selections <<< "mysql-server-5.7 mysql-server/root_password_again password $temp_mysql_password"
sudo apt-get -y install mysql-server-5.7
sudo apt-get install curl -y
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs -y
curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo apt-get update && sudo apt-get install influxdb -y
sudo service influxdb start

node -v
npm -v
java -version
javac -version
mysql --version
mvn -version
influxd
